### PR TITLE
DATAES-219 Developments for querydsl-elasticsearch integration.

### PR DESCRIPTION
**Pull request by kevinleturc**

### CODE REVIEW

**Comment by martin-g** [comment]
This PR has very high quality. I'm not sure why there is no feedback on it for almost 50 days now.
Good work, @kevinleturc !

**Comment by olivergierke** [comment]
Ping @mohsinh.

**Comment by kevinleturc** [comment]
Hello,
Thanks @martin-g, just try to add good features I used with spring-data-mongodb.

Currently the pull request can not be merged due to upgrade to elasticsearch 2.x. @gkathire proposed a pull request to https://github.com/querydsql/querydsl-contrib for elasticsearch 2.x. I'll ask @timowest to merge it in order to change this PR.

@mohsinh, is it something we can discuss to merge ?
@olivergierke, as querydsl version is not aligned with querydsl-contrib, do we need an additional property for querydsl-contrib ? What about querydsl-apt version which is shared across two projects ? Maybe we can discuss it with @timowest ?

PS: The querydsl-contrib PR : https://github.com/querydsl/querydsl-contrib/pull/15

**Comment by akonczak** [comment]
For more info please check - https://jira.spring.io/browse/DATAES-219

**Comment by akonczak** [comment]
We are still waiting for QueryDSL team for release of 'querydsl-contrib' project.

**Comment by bryancuster** [comment]
https://github.com/querydsl/querydsl-contrib/pull/19 looks to have been merged, is there anything else blocking the support?

**Comment by kevinleturc** [comment]
There is, querydsl/querydsl-contrib#19 brought support for ES 2.x. And now spring-data-elasticsearch support ES 5.x.
This PR could be a candidate for 2.1.x branch if it's possible, but we'll miss support on latest version.

**Comment by ft0907** [comment]
@olivergierke  @kevinleturc  
When is the es5.x version available to support querydsl ？
Or have no follow-up information to support？

**Comment by sothawo** [comment]
closing this PR, as the latest supported version of Elasticsearch in Querydsl is 2.2.2 whic is not supported by Spring Data Elasticsearch anymore

**Pull request closed without merging**
