### PR TITLE
DATAES-323 - Use JsonProperty in MappingBuilder.

### PR DESCRIPTION
**Pull request by ivangreene**
Honor the JsonProperty annotation for field names
when building mappings.

- [X] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [X] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAES).
- [X] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [X] You submit test cases (unit or integration tests) that back your changes.
- [X] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by ivangreene** [comment]
Point of note: [line 375](https://github.com/spring-projects/spring-data-elasticsearch/blob/436a3213fcd6a8073110b9a2a94784952765ceaf/src/main/java/org/springframework/data/elasticsearch/core/MappingBuilder.java#L375) in MappingBuilder#isIdField still uses field.getName() because I believe that the persistent property will be using the original field name.

**Comment by GitProBo** [comment]
hi @ivangreene : I found this solution deal with output format, and not useful for ElasticsearchRepository for input fieldname

TestEntity
	@JsonProperty("format_id")
	private Integer formatId;

TestRepository
findAll:   
Test(id=AWnBoHGhRre5ZNxJ_Lxx, formatId=8)

findByFormatId
null

**Comment by ivangreene** [comment]
@GitProBo I'm not entirely sure what you mean. Can you point me to a test or include a snippet where this is an issue? Happy to add a test case

**Comment by GitProBo** [comment]
> @GitProBo I'm not entirely sure what you mean. Can you point me to a test or include a snippet where this is an issue? Happy to add a test case



> @GitProBo I'm not entirely sure what you mean. Can you point me to a test or include a snippet where this is an issue? Happy to add a test case

report updated

**Comment by ivangreene** [comment]
Ok I understand. I will look into this more and try to figure out a solution. Thanks for the comment @GitProBo

**Comment by roblankey** [comment]
And here I thought I was going crazy that this wasn't working any longer. I understand that the autoquerying with the repository potentially falls over as soon as you add JsonProperty renames, and if removing it was explicit in 3.1.0.RELEASE, then it seems like a valid reason.

I wonder if it's worth adding that as another configuration option to enable JsonProperty usage with the caveat that if you, as the dev user, add the JsonProperty attribute and enable the processing of JsonProperty attributes, that you're also going to need to implement your own @Query methods for those fields.

**Comment by ivangreene** [comment]
@roblankey interesting idea for a config option. I myself would opt for that because in my org we are not really using the repositories anyway.
Would like to get some input from a committer on how we should proceed with fixing this.

@xhaggi I see you are assigned on the Jira. Any input on this issue and the type of solution you would like to see? And if not can you tag another committer. Thanks

**Comment by sothawo** [comment]
I don't think that adapting the Mapping in the index is enough. 
When an document is written to the index, the `SpringDataSerializerModifier` from the `SpringDataElasticsearchModule` drops the PropertyWriter for the JsonProperty annotated property because the name of the beanPropertyWriter (that's coming from the annotation) does not match the name of the PersistentProperty.
I'm not sure, if it's better to change this place as well to check for the JsonProperty annotation or to modify the PersitentProperty.

**Comment by xhaggi** [comment]
This will be superseded by #270

**Comment by ivangreene** [comment]
Closing in favor of #270

**Pull request closed without merging**
