### PR TITLE
DATAES-402 - fixing paging information

### PR DESCRIPTION
**Pull request by zigterman**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAES).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by maxtuzz** [comment]
Nice!

**Comment by tanadeau** [comment]
Can this get merged? This seems like an easy fix for a bad issue.

**Comment by maxtuzz** [comment]
It's a little worrying that it takes so long to merge such a simple change. 

In the meantime I've had to reimplement the bugged classes with fixes and overwrite like so: 

```java
        AggregatedPageImpl<Practitioner> aggregatedPage = (AggregatedPageImpl<Practitioner>) page;

        return new AggregatedPageMyAppImpl<>(page.getContent(),
                pageable,
                page.getTotalElements(),
                aggregatedPage.getAggregations());
```

Which is super messy but does the job until this release is out.

**Comment by tanadeau** [comment]
Ping. Can this be merged?

**Comment by zigterman** [comment]
I think it can be merged, expected that is should be in 3.1 but as I see the M1 release for that it is not in it.

I also updated this ticket (https://jira.spring.io/browse/DATAES-402) to get more information, but since I created it there is no response on it from the team.

**Comment by schleifer-john** [comment]
Hello @olivergierke, @christophstrobl, @mp911de.  I attended the 2017 SpringOne conference and in Phil Webb's keynote presentation he showed that the Spring Data Elasticsearch project is one of the more popular projects used (https://content.pivotal.io/springone-platform-2017/phil-webb-at-springone-platform-2017 around the 11 minute mark).

This project is listed as a "Community Module".  As evidenced here, the community is making important contributions to fix critical bugs, but the original maintainers (@mohsinh, @akonczak) are no longer active and as a result this project gets no Elasticsearch specific bug fixes or critical updates outside of the Spring Core Team maintenance work.

Meanwhile, Elasticsearch continues to put out new releases, and this popular Spring Cloud project is several major versions behind.  Support for Elasticsearch version 2.4.x, which is what the last official release that this project supports, reaches end of life February 28, 2018.  https://www.elastic.co/support/eol

As evidenced by your own analytics, Spring Data Elasticsearch is more popular than officially maintained projects like Spring Data Solr and Cassandra projects.  Is there a process for this project to move from a "Community Module" to a "Main Module"?  Is there a process for new community maintainers to be appointed so that critical bug fixes can be reviewed and merged?

I would like to continue using this project, but my organization is faced with the reality of either forking this project or rewriting our data access layers to leverage the Elasticsearch API directly due to this project being outdated and not actively maintained.  Are there any updates or recommendations that you can provide for developers facing my situation?

Thanks!

**Comment by tanadeau** [comment]
@schleifer-john My project is in the exact same position. Unless something happens soon, we're going to fork a new project that just has the parts we use (mostly index and mapping creation via annotations and a few other small parts).

**Comment by pasali** [comment]
Unfortunately i had to fork this repo and made my own implementation with official es high level rest client. Official client is not ready yet but es team is working hard to make it complete.  You can check it out from here : https://github.com/elastic/elasticsearch/issues/27205

**Comment by zampettim** [comment]
This seems like a critical fix. Can one of the committers comfirm when this will be merged in?

**Comment by akonczak** [comment]
rebased/merged to master 
Thank you for your the contribution into project.

**Pull request closed without merging**
