### PR TITLE
DATAES-183 possibility to override the Mapper on morelikethis queries

### PR DESCRIPTION
**Pull request by pedivo**

### CODE REVIEW

**Comment by mohsinh** [comment]
Thanks for the PR, i can see 2 PR with similar name and JIRA ticket reference. 

Can you please close one of this ? or merge this in one please ?

**Comment by pedivo** [comment]
@mohsinh i've closed the #113.
However #113 is for 1.1.x versions and #112 for the 1.3.x versions that's why i did 2 PR with the same name.

**Comment by mohsinh** [comment]
Thanks, we will review it soon.

we will add it to subsequent releases once it is merge to master. 

If you're a first-time submitter, make sure you have completed the Contributor's License Agreement form for SpringSource. which is at https://support.springsource.com/spring_committer_signup

Project : spring data access
Project Lead : Oliver Gierke

More information about contribution can be found at

https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.md

**Comment by mohsinh** [comment]
MLT is removed from elasticsearch 2.x, and we have rewrite the code using moreLikeThisQuery().

**Pull request closed without merging**
