### PR TITLE
DATAES-673 Create a Ssl Rest Client using SslContext and HostnameVerifier

### PR DESCRIPTION
**Pull request by henriqamaral**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@henriqamaral Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=334)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=334) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@henriqamaral Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=334)!

**Comment by sothawo** [comment]
Thank your for this PR, it has been merged.

**Comment by henriqamaral** [comment]
> Thank your for this PR, it has been merged.

Hi @sothawo thanks, Should I open a new PR to 3.2.x?

**Comment by sothawo** [comment]
no, we normally merge bugfixes into released versions, so I did not do this here. This change was so small I think I will do that this evening

**Pull request merged**
