### PR TITLE
Added @DynamicTemplates annotation

### PR DESCRIPTION
**Pull request by kukisak**
Hi, I added new DynamicTemplates annotation to enable dynamic mapping of indexAnalyzer and searchAnalyzer on fields annotated like @Field(type = FieldType.Object). This is alternative to static mapping via @Mapping annotation but more flexible. We found it very useful in our project. Please pull it to master branch if you find it handy.

Petr

### CODE REVIEW

**Comment by jbesta** [comment]
+1

**Comment by javamachr** [comment]
+1

**Comment by molotowitz** [comment]
Any news on this?

**Comment by Rajind** [comment]
Is there no other way to define dynamic template mapping in spring-data-elasticsearch other than this pull request ?

**Comment by kukisak** [comment]
Hi, sorry for late reponse. I overlook your comment. I looked for some way to define it but this feature is missing in spring-data-elasticsearch. Thats the reason for this pull request. But you can rewrite it by your own as you wish.

**Comment by kukisak** [comment]
@Rajind are there any news about this feature? We would like to update to newer version of spring-data-elasticsearch but we are blocked by this feature. We will appreciate if you merge it to master and close it.

**Comment by Rajind** [comment]
@kukisak I moved to native elastic-search for my project and hence I have no news on this. Regarding merging, I believe you should ask @mohsinh

**Comment by kukisak** [comment]
@mohsinh Do you have any news about this? We will appreciate your collaboration.

**Comment by mohsinh** [comment]
@kukisak 

Hello, 

Sorry for late reply. 

Can you rebase your branch with master ? also you need to add test(s) to cover the feature you are proposing. we will review it asap once you rebase and add some working test.

**Comment by kukisak** [comment]
@mohsinh 

Hi,

I updated code, tests and rebased it to ES 2.1.0 master branch. You can now review it. Thanks.

**Comment by kukisak** [comment]
@mohsinh any news?

**Comment by addmaths07** [comment]
I'm waiting for the same!

**Comment by ssudekum** [comment]
+1

**Comment by pivotal-issuemaster** [comment]
@kukisak Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=132) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kukisak Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=132)!

**Comment by sothawo** [comment]
implemented and already merged with #238

**Pull request closed without merging**
