### PR TITLE
Add a flag in configuration to consider nested repositories

### PR DESCRIPTION
**Pull request by kevinleturc**
Here is a pull request to enable the nested repositories in the configuration.

### CODE REVIEW

**Comment by kevinleturc** [comment]
Hi,
Any news on this ?
Regards.

**Comment by thomasdarimont** [comment]
Hi Kevin,

thanks for the PR! We'll have a look at that - I filed https://jira.spring.io/browse/DATAES-147 to track this.

Cheers,
Thomas

**Comment by kevinleturc** [comment]
Hi Thomas,
Thanks for Jira, I will track it.

Yes I've already signed the CLA, my CLA number is 89220140815073325.

Regards

**Comment by kevinleturc** [comment]
I close this Pull Request as the commit has been merged in PR #89.

**Pull request closed without merging**
