### PR TITLE
DATAES-503 - Added missing copy_to property to @Field annotation.

### PR DESCRIPTION
**Pull request by andre2k2**
Hi, I'd like to suggest include copy_to property into Field annotation. Would be nice to have it in next release.

### CODE REVIEW

**Comment by TittoProof** [comment]
this is an important improvement, can you merge for the next release?

**Comment by frascuchon** [comment]
Hi, 

Any progress with this PR? It's a good improvement 

Thanks!

**Comment by mbabauer** [comment]
What ever happened to this PR?  A copy_to option on Field would be most helpful.

**Comment by xhaggi** [comment]
Replaced by #227

**Pull request closed without merging**
