### PR TITLE
DATAES-188: Source filtering feature Implementation

### PR DESCRIPTION
**Pull request by jtsiros**
This implements source filtering to allow control over what field(s) are returned in the _source field with every hit.

See https://www.elastic.co/guide/en/elasticsearch/reference/1.6/search-request-source-filtering.html

### CODE REVIEW

**Comment by konfetov** [comment]
Please merge the code to the master and roll out as soon as possible. It is very great to filter the source in basic ElasticsearchTemplate.

**Comment by sokersten** [comment]
+1

**Comment by piteron** [comment]
+1

**Comment by hedgerocker** [comment]
+1

**Comment by flefebure** [comment]
+1

**Comment by MikE87** [comment]
+1

**Comment by mohsinh** [comment]
i have to merge manually due to merge conflicts. 

Thanks for the PR

**Pull request closed without merging**
