### PR TITLE
DATAES-671 - Missing indicesOptions support for scrolling queries

### PR DESCRIPTION
**Pull request by sirgyula**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAES).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by sothawo** [comment]
thank you for this PR

**Comment by sirgyula** [comment]
thanks, have a nice day!

**Comment by sirgyula** [comment]
quick question here, will the fix be released in 3.2.1?

**Comment by sothawo** [comment]
done.

**Pull request merged**
