### PR TITLE
DATAES-166: improve scroll implementation to support scroll without scan

### PR DESCRIPTION
**Pull request by xhaggi**
This PR improves the scroll implementation to support scrolling without the search type "scan". It adds a new `ScrollPage` interface to include the `scrollId`, because the initial search request and each subsequent scroll request returns a new scroll id and only the most recent scroll id should be used.

For more details see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html

### CODE REVIEW

**Comment by xhaggi** [comment]
I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

**Comment by xhaggi** [comment]
@mohsinh any chance to get this reviewed?

**Comment by xhaggi** [comment]
It would be nice to get some feedback on this. It's a valid fix + improvement and I'm sure there are other that would like to see this included in the next release.

**Comment by xhaggi** [comment]
rebased against master, hope this will be reviewed soon.

**Comment by bouncehead13** [comment]
@mohsinh I would like to second the comments made above to get this merged in for a future release. We noticed this exact problem reading through our logs with a lot of errors stating the provided `scrollId` has expired. This is caused by using the first `scrollId` rather than the new `scrollId` returned from the `SearchResponse`. @xhaggi has a solution that works beautifully. We even went as far to pull his code into our production codebase.

To prove my point even more, code was recently merged that follows this same principal. Here is the line I am referring to in this [Pull Request](https://github.com/spring-projects/spring-data-elasticsearch/pull/106/files#diff-14f586e65b5fba7073253c2b363704a8R392). You can see after each executed scroll, the `scrollId` is updated from the `SearchResponse`. However, this was only added to the streaming capabilities.

Please take a look over this pull request.

**Comment by xhaggi** [comment]
@mohsinh please let me know if you are planing to accept this PR and I'll do another rebase against the current master.

**Comment by xhaggi** [comment]
@mohsinh and @bouncehead13 rebased against master again .. hope someone could review the PR.

**Comment by xhaggi** [comment]
@akonczak ping you too

**Comment by xhaggi** [comment]
Rebased once again. Is there any sign of life here .. a yes looks good or no we don't merge your crap would be nice. We all spent our spare time in contributing to this project and only want a reaction. This PR is open since 29 Sep 2015 and nobody of the team reacted on it.

**Comment by xhaggi** [comment]
I think this is now obsolete.

**Pull request closed without merging**
