### PR TITLE
DATAES-163 Add support of UUID type as primary key

### PR DESCRIPTION
**Pull request by Akuka**
I received this exception when I tried to use UUID as the key for an ElasticSearch Repository:
```
Caused by: java.lang.IllegalArgumentException: Unsuppored ID type class java.util.UUID
	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactory.getRepositoryBaseClass(ElasticsearchRepositoryFactory.java:79) ~[spring-data-elasticsearch-1.3.2.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepositoryInformation(RepositoryFactorySupport.java:238) ~[spring-data-commons-1.11.2.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:181) ~[spring-data-commons-1.11.2.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:251) ~[spring-data-commons-1.11.2.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:237) ~[spring-data-commons-1.11.2.RELEASE.jar:na]
	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactoryBean.afterPropertiesSet(ElasticsearchRepositoryFactoryBean.java:55) ~[spring-data-elasticsearch-1.3.2.RELEASE.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 32 common frames omitted
```
So I add support for UUID types in Spring Data Elastic Search

### CODE REVIEW

**Comment by akonczak** [comment]
Please sign a contributor agreement  https://support.springsource.com/spring_committer_signup, we are working on your PR

**Comment by akonczak** [comment]
Changes has been merged into https://github.com/spring-projects/spring-data-elasticsearch/tree/DATAES-163

**Comment by mksasi** [comment]
This is a needful change, can this be pushed to 2.x branch as well?

**Comment by bluestix** [comment]
Is this going to be in any of the 2.x releases? It's a blocker for me. Don't really want to do manual save/retrieve and I am not switching my id types.

**Comment by akonczak** [comment]
Thank you very much for your PR. Changes has been merged to master.

**Pull request closed without merging**
