### PR TITLE
DATAES-421 - Update ES to 6.1.0

### PR DESCRIPTION
**Pull request by rivergod**
- [X] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [X] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAES).
- [X] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [X] You submit test cases (unit or integration tests) that back your changes.
- [X] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by jordanbaucke** [comment]
@rivergod I'm trying to build and connect this with Spring Boot 1.5.9, when I include the required version of `spring-data-core`, and the related dependencies it breaks a lot of things in the rest of my application that rely on spring-boot. 

Any advice?

I pulled your fork, and ran `mvn install`, but it didn't include any dependencies, so I built it with dependencies and directly added the `.jar` file to my classpath, any other advice?

**Comment by donrw** [comment]
@jordanbaucke I think you will need to go Spring Boot 2.0 and Spring Framework 5 and Spring Data Kay Release Train.  I did take a crack at the migration to see what the head aches were. I can't find my notes right now.  But, from memory, Optional showed up on a few APIs and a couple classes moved to different packages was the majority of the compile errors.  I ended up having to switch to work on something else before I could check for run time problems.

**Comment by tfeiner** [comment]
is there a time plan when this PR is merged? It would be really great to use Spring Data Elasticsearch with ES 6.2.x

**Comment by djogss** [comment]
I can't get it working using as there isn't a way to create ElasticsearchOperations bean in this version.
spring-boot 2.0 elasticsearch 6.x spring-boot-data 3.1

Has anyone else had any luck with this?

**Comment by akonczak** [comment]
Hi All
@olivergierke and @christophstrobl - me and @mohsinh did a review and also moved to latest version of ES. All changes are in the branch - https://github.com/spring-projects/spring-data-elasticsearch/tree/DATAES-421-review.

@christophstrobl if you happy we can merge DATAES-421-review and close this PR(I will leave this branch unmerge for next 2 day to give you a chance to look into it.)

**Comment by olivergierke** [comment]
Thanks for taking care of this, @akonczak!

**Pull request closed without merging**
