### PR TITLE
DATAES-274 prevent NPE in FacetedPageImpl

### PR DESCRIPTION
**Pull request by pkraeutli**
I only added the `if (aggregations != null) {` in line 91. The diff looks big because of the indented block.

### CODE REVIEW

**Comment by pkraeutli** [comment]
I agree, will change it. I did it that way to be consistent with the `if` in line 88.

**Comment by sreekanthsnair** [comment]
I'm also facing the same issue after upgrading form 2.0.6.RELEASE to 2.1.1, will be hot fixed to 2.1.1.RELEASE sooner elase may i know which will be the safest version to upgrade?

**Comment by CosminCH** [comment]
We are having the same problem with 2.1.1.RELEASE...

**Comment by a-poptsov** [comment]
as a workaround before serialization we are doing a trick like this:
```java
 private <T> Page<T> fixEmptyPage(Page<T> page) { 
     AggregatedPageImpl<T> aggregatedPage = (AggregatedPageImpl<T>) page;
        Aggregations aggregations = aggregatedPage.getAggregations();
        if (aggregations == null) {
            Field field = ReflectionUtils.findField(AggregatedPageImpl.class, "aggregations");
            ReflectionUtils.makeAccessible(field);
            ReflectionUtils.setField(field, aggregatedPage, InternalAggregations.EMPTY);
            return aggregatedPage;
        }
        return page;
    }

**Comment by CosminCH** [comment]
@a-poptsov thank you for the workaround, I prefer not to do your workaround (would have to add it with todo, just more technical debt..) as I am sure the PR is going to be merged soon. Right, @evelan ?

**Comment by shkmaaz11** [comment]
Hi,
I have the 2.1.1.RELEASE. but still I am facing this issue.

The stack trace is as below


java.lang.NullPointerException: null at org.springframework.data.elasticsearch.core.FacetedPageImpl.processAggregations(FacetedPageImpl.java:89) ~[spring-data-elasticsearch-2.1.0.RELEASE.jar:na]
	at org.springframework.data.elasticsearch.core.FacetedPageImpl.getFacets(FacetedPageImpl.java:68) ~[spring-data-elasticsearch-2.1.0.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_60]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_60]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:664) ~[jackson-databind-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690) ~[jackson-databind-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) ~[jackson-databind-2.8.6.jar:2.8.6]
	

Can please suggest a work around on this issue.

**Comment by sreekanthsnair** [comment]
2.1.2 and 2.1.3 also having the same issue. may i please know, does this issue can be hotfixed to any of the 2.1.X branch ?

**Comment by maxtuzz** [comment]
I am also having the same problem. The fix above works but would be great if we didn't need it.

**Comment by CrAzE124** [comment]
+1 having similar problems.

**Comment by sreekanthsnair** [comment]
@olivergierke can you please tell us when this is going to be fixed and in which release, due to this issue we could not upgrade the entire spring data stack.

**Comment by olivergierke** [comment]
Unfortunately I can't, as the project is a community project and not run by the core Spring Data team.

**Comment by sepe81** [comment]
@akonczak can you please tell us when this is going to be fixed and in which release, due to this issue we could not upgrade the entire spring data stack.

**Comment by mohsinh** [comment]
Hello @sepe81 

Can you please add at least one test in ElasticsearchTemplateFacetTests.java to cover this bug ?

**Comment by pkraeutli** [comment]
I added a test @mohsinh
Sorry, didn't see your comment earlier.

**Comment by pkraeutli** [comment]
@mohsinh is the test ok like that? Can this be merged?

**Comment by mohsinh** [comment]
merged with master.

**Comment by liuyatao** [comment]
I am using  the spring boot.The spring boot version is 1.5.6 RELEASED,the spring data elasticsearch version is 2.16, the elasticsearch version is 2.4.5 . Still have the problem:    

nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.springframework.data.elasticsearch.core.aggregation.impl.AggregatedPageImpl["facets"])

**Comment by sepe81** [comment]
@liuyatao According to https://jira.spring.io/browse/DATAES-274 this has been fixed only for version 3.0 RC1 (Kay). I can approve that this is not fixed for version spring-data-elasticsearch-2.1.6 and spring-boot 1.5.6 still has the problem.

@mohsinh Could this also be cherry-picked for the 2.1.x branch (preferably 2.1.7)?

**Comment by CosminCH** [comment]
How many thumbs up are needed for a small fix to be backported?

**Comment by sreekanthsnair** [comment]
This is not backported to any 2.1.x releases...!, Should we have to create a new issue in spring Jira?

**Pull request closed without merging**
