### PR TITLE
DATAES-643: Added searchType to prepareSearch() in RestTemplate

### PR DESCRIPTION
**Pull request by glenroy37**
- [ x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAES).
- [x ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@glenroy37 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=310)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=310) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@glenroy37 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=310)!

**Comment by sothawo** [comment]
Thank your for this contribution; can you please:

- add the corresponding code to the `ElasticsearchTemplate` and `ReactiveElasticsearchTemplate` classes as well
- change this PR to merge into the 4.0.x branch, as we are not adding new features in the 3.2.x branch anymore before the relase

**Comment by Flexba** [comment]
Personally, I'd say that ignoring the setting is a bug rather than taking care of it would be a feature

**Comment by glenroy37** [comment]
The `ElasticSearchTemplate `already does this on line 1084 in `prepareSearch(Query query, @Nullable ElasticsearchPersistentEntity<?> entity`). We're upgrading our application from Transport Protocol to REST, so not setting the type in the RestTemplate breaks it.

I'll add it in the ReactiveElasticSearchTemplate.

**Comment by sothawo** [comment]
sorry, I missed that it was already implemented in `ElasticsearchTemplate`, so this is definitely a bug preventing from migrating to the Rest client. 
So thanks for the contribution, merged into master so it will be in the 3.2. release

**Pull request merged**
