### PR TITLE
DATAES-93 Allow Spring EL usage in index name attribute of @Document

### PR DESCRIPTION
**Pull request by greyfairer**
See https://jira.spring.io/browse/DATAES-93
Allows e.g. @Document(indexName = "#{'${ugcmanager.elasticsearch.indexPrefix}'}-ugc-manager-cities")

### CODE REVIEW

**Comment by pradeepcheers** [comment]
Same as @herotl2005 mentioned. I tried with spring-data-elasticsearch version 1.1.2.RELEASE but as per the jira (https://jira.spring.io/browse/DATAES-93) it is fixed in version 1.1 RC1

**Comment by vdbxavier** [comment]
same problem with 1.2.0.RELEASE

**Comment by greyfairer** [comment]
Hi,

I recently used it as follows in my application: 

    <bean id="indexPrefix" class="java.lang.String">
        <constructor-arg value="${env}-myapp"/>
    </bean>

    @Document(indexName = "#{@indexPrefix}-index", type = "revision")
    @Setting(settingPath = "/es/revision-settings.json")
    @Mapping(mappingPath = "/es/revision-mappings.json")
    public class RevisionEsEntity {
    }

I'm not sure why it wouldn't work with `"#{'${elasticsearch.index.name}'}"`...

**Comment by vdbxavier** [comment]
it's works with bean ; thx

**Comment by daveyx** [comment]
thx @greyfairer with spring-data-elasticsearch:3.0.5.RELEASE it also works:

entity:
`@Document(indexName = "#{@indexPrefix}-index", type = "testtype", createIndex = false)`

config:
```
@Value("${es.index.test1}")
private String esIndex;

...

@Bean
public String indexPrefix() {
	return esIndex;
}
```

**Comment by jvmlet** [comment]
Sorry for resurrecting  the 7 years old thread, but how do I reference Document's field in index expression ?

````java
@Document(indexName="#{@currentBean.prop}-log")
class MyBean{
@Getter @Setter
private String  prop;
}

MyBean b = new MyBean();
b.setProp("someValue");
repository.save(b); // should be saved in index someValue-log

Thanks
````

**Comment by sothawo** [comment]
The SpEL resolution does not happen in the context of the entity object, so this won't work. 
You can implement this by using Spring Data Repository customization, I wrote a blog post how to do this: https://www.sothawo.com/2020/08/use-an-index-name-defined-by-the-entity-to-store-data-in-spring-data-elasticsearch-4-0/

**Comment by jvmlet** [comment]
Thanks, @sothawo , exactly what I was looking for. Any plans to support this out-of-the-box ?

**Comment by sothawo** [comment]
In the SpEL evaluation? No; when discussing with the Spring Data Team, there was the decision to not add this additional SpEL context resolution.
But I think with the the repository customization it's easy to get this functionality, especially a the customizations can override the default repository methods like `save(T)`

**Pull request closed without merging**
