### PR TITLE
DATAES-214 - ElasticsearchTemplate's prepareSearch(Query query) metho…

### PR DESCRIPTION
**Pull request by Iamcerba**
…d should use getOffset().

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAES).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by sothawo** [comment]
Thank you for the PR; please don't delete the template text for PRs but check that all the requirements are met and tick them off.

Please target this PR to the master branch, we will backport necessary stuff to the 3.2.x branch.

**Comment by Iamcerba** [comment]
> Thank you for the PR; please don't delete the template text for PRs but check that all the requirements are met and tick them off.
> 
> Please target this PR to the master branch, we will backport necessary stuff to the 3.2.x branch.

Hey @sothawo,

I've checked the master branch and nothing should be changed there, everything is working as intended. But 3.2.x could be patched.

**Comment by sothawo** [comment]
4: you should make sure that the changes are covered by existing tests or write new ones.
5: why not?

for the target branch leave it on 3.2

**Comment by Iamcerba** [comment]
@sothawo,

Thank you for merging and polishing. I just wanted to be consistent with Reactive client: https://github.com/spring-projects/spring-data-elasticsearch/blob/bacad5ca0ce9fff888c574fc5287dc4f474705e0/src/main/java/org/springframework/data/elasticsearch/core/ReactiveElasticsearchTemplate.java#L362

**Comment by sothawo** [comment]
wasn't strictly necessary, as '%s' would call `toString()` on the Integer, and that works as well. Must be something deep in the back of my brains from old times when programming in C, there this would have produced a segmentation violation.

**Pull request merged**
