### PR TITLE
Feature/id source map

### PR DESCRIPTION
**Pull request by mikaellemos033**
I'm adding a new annotation for JPA not to make `@Field ("id")` as the primary key, so I can get the value of `_source.id`

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mikaellemos033 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=1762)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=1762) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mikaellemos033 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-elasticsearch&pullRequestId=1762)!

**Comment by sothawo** [comment]
Before creating a pull request open an issue describing the problem you have, so we can have a look at the problem and at possible solutions.

**Comment by mikaellemos033** [comment]
correction made from version 4.2

**Pull request closed without merging**
