### PR TITLE
DATAES-290 - Make joda-time dependency optional.

### PR DESCRIPTION
**Pull request by ptahchiev**
This PR adds a check if joda-time is in the classpath before registering the joda-time converters. This is the first step towards making joda-time as optional dependency. However it is also being used here:

https://github.com/spring-projects/spring-data-elasticsearch/blob/master/src/main/java/org/springframework/data/elasticsearch/core/FacetedPageImpl.java#L161

and this code will have to be deleted (it is deprecated atm).

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAES).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by xhaggi** [comment]
@ptahchiev Please cleanup/fix your commit history. One commit for your changes should be enough.

**Comment by ptahchiev** [comment]
@xhaggi I would really appreciate some help here. Do you know how to do this?

**Comment by xhaggi** [comment]
@ptahchiev first please read our Spring Data contribution guidelines carefully again. Your commit message does not fit. Next it would be the easiest way if you squash the last 3 commits and rebase them against the upstream master. This page should helps to understand what's possible https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History especially section _Squashing Commits_

**Comment by ptahchiev** [comment]
I've created a new PR: https://github.com/spring-projects/spring-data-elasticsearch/pull/213

**Pull request closed without merging**
