### PR TITLE
DATAES-847 Add DateFormat values for epoch_millis and epoch_second; adopt week_year name changes

### PR DESCRIPTION
**Pull request by timtebeek**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAES-847).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by timtebeek** [comment]
There's a few more oddities when comparing the fields in DateFormat with the fields listed at ES:
https://github.com/timtebeek/spring-data-elasticsearch/blob/master/src/main/java/org/springframework/data/elasticsearch/annotations/DateFormat.java
https://www.elastic.co/guide/reference/mapping/date-format
```
official elasticsearch docs				      |	DateFormat class
week_date_time_no_millis				      |	weekDateTimeNoMillis
weekyear						      |	week_year
weekyear_week						      |	weekyearWeek
weekyear_week_day					      |	weekyearWeekDay
```

**Comment by timtebeek** [comment]
I'm guessing we'll want to switch the offending constants over to the official references again, as I'm not sure the current camelCased values even work. But also don't want to introduce a potentially breaking change if they do still work, so I'm leaving that up the the maintainers to decide whether we want to change those additional fields.

**Comment by timtebeek** [comment]
It seems the old values originate with any pre ES2:
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/mapping-date-format.html
Starting with 2.0 the fields seem to have been renamed:
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/mapping-date-format.html
As such it would seem the current values wouldn't work and fixing them here would be sensible.

**Comment by timtebeek** [comment]
Awesome; thanks for the quick review & merged; surprised how easy both the fix was and the process to get it approved! :)

**Comment by sothawo** [comment]
You're welcome! (and I could try the new integrated PR feature of IntelliJ IDEA 2020.2 EAP)

**Pull request merged**
