### PR TITLE
Added support for "geohash_prefix" and "geohash_precision" on GeoPoin…

### PR DESCRIPTION
**Pull request by dandonovsc**
…tField annotation

### CODE REVIEW

**Comment by dandonovsc** [comment]
Added support for "geohash_prefix" and "geohash_precision" on GeoPointField annotation

**Comment by akonczak** [comment]
Thanks for pull request. 

Would you be able to sign the contributor's agreement.

https://support.springsource.com/spring_committer_signup

**Comment by dandonovsc** [comment]
I did using my personal email ( dian.andonow@gmail.com<mailto:dian.andonow@gmail.com> ). I would like to be registered under this email. Let me know if there is a technical issue and you need to me to sign the agreement under dandonov@sharecare.com<mailto:dandonov@sharecare.com>


Individual Contributor Agreement
Hello Dian Andonov

Thank you but our records indicate that you have already accepted the individual contributor agreement. If you are interested in participating in an additional Spring project, please contact the appropriate project lead and indicate that you have already signed the Spring Contributor Agreement. Once signed agreement covers participating in as many Spring projects as you need.

Your confirmation number is: 127420150622033520

On Sep 18, 2015, at 11:27 AM, Artur Konczak <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for pull request.

Would you be able to sign the contributor's agreement.

https://support.springsource.com/spring_committer_signup

**Comment by akonczak** [comment]
I have added your name/alias with agreement number in wiki to avoid asking about it in the future. 
Thank you one more time for the contribution.

**Pull request closed without merging**
