### PR TITLE
DATAES-141 Mapping Context is null in DefaultResultMapper when using custom Entitymapper

### PR DESCRIPTION
**Pull request by kevinleturc**

### CODE REVIEW

**Comment by kevinleturc** [comment]
Hi,
Any news on this ?
Regards.

**Comment by kevinleturc** [comment]
Hi,
Any news on this ?
Regards

**Comment by kevinleturc** [comment]
Hi,
Any news on this ?
Regards

**Comment by akonczak** [comment]
Changes has been marge to master, Thank you for your contribution.

**Pull request closed without merging**
