### PR TITLE
5.x

### PR DESCRIPTION
**Pull request by thirusams**
- [ ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAES).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by jfine** [comment]
👍 Looking forward to 5.x support!

**Comment by sachinmstack** [comment]
Hi,
  I would like to know whether current spring data elasticsearch will support elastic 5.x ? If not please tell me by when it will do ?

**Comment by maxtuzz** [comment]
Looking forward to this!

**Comment by mohsinh** [comment]
redundant to [other pull request](https://github.com/spring-projects/spring-data-elasticsearch/pull/170)

**Comment by virendrapatidar** [comment]
I am getting below exception with elastic search 5.4.1

```

[2017-06-06T15:43:56,166][WARN ][o.e.t.n.Netty4Transport  ] [B752Y9b] exception caught on transport layer [[id: 0x41332c6d, L:/127.0.0.1:9300 - R:/127.0.0.1:51886]], closing connection
java.lang.IllegalStateException: Received message from unsupported version: [1.0.0] minimal compatible version is: [5.0.0]
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1363) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) ~[transport-netty4-5.4.1.jar:5.4.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
```

**Pull request closed without merging**
