### PR TITLE
DATAES-709 - Add parameter to include defaults on get settings

### PR DESCRIPTION
**Pull request by xhaggi**
https://jira.spring.io/browse/DATAES-709

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAES).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by xhaggi** [comment]
@sothawo IMO the method name should be `getSettings()`. Should we mark the current one as deprecated, add the new one (separate commit) and after that I add the overloads?

**Comment by sothawo** [comment]
I just had a look at the Elasticsearch docs. The `RestHighLevelClient` can execute a `GetSettingsRequest`. So we should use that instead of doing the request with the low level client. I assume that the existing code here comes from the times when the high level client did not yet support this request (as far as I remember that was in ES 5). 
This would then enable us for both cases (`DefaultIndexOperations`and `DefaultTransportIndexOperations`) to use the same code to parse the response and move that to `AbstractDefaultIndexOperations`.

As for the naming: I think we should add the different `getIndexSettings()` methods to the `IndexOperations` interface and document them with `since 4.0`. The existing should then be changed to deprecated with a default implementation that uses the new one:
```
	/**
	 * Get settings for a given indexName.
	 *
	 * @param indexName the name of the index
	 * @return the settings
	 * @deprecated since 4.0, use getSettings(indexName) instead.
	 */
         @Deprecated
	default Map<String, Object> getSetting(String indexName) {
		return getSettings(indexName);
	}
```
No need for a different issue for that.

**Comment by xhaggi** [comment]
@sothawo Thanks for pointing out that the HighLevelClient now supports it. I have addressed your comments and force-pushed the changes.

**Comment by sothawo** [comment]
As the `getIndexSettings()`methods are part of the `IndexOperations`interface I would not add _Index_ in the method name. I think, `IndexOperations.getSettings(...)` is enough. 

Having looked at that again, I think we can even remove the `getSetting(...)`methods from `IndexOperations`, as this interface was just introduced in the master branch; no need to deprecate something that was never released.

But we would need to change the deprecated definitions of the old methods in `ElasticsearchOperations`:

```
	/**
	 * Get settings for a given indexName.
	 *
	 * @param indexName the name of the index
	 * @return the settings
	 * @deprecated since 4.0, use {@link IndexOperations#getSettings(String)} )} instead}
	 */
	@Deprecated
	default Map<String, Object> getSetting(String indexName) {
		return getIndexOperations().getSettings(indexName);
	}
```

Sorry, hadn't noticed that before.

**Comment by xhaggi** [comment]
@sothawo all done and force-pushed.

**Pull request merged**
