### PR TITLE
DATAES-595 - Support for setting Elasticsearch Preference in the Quer…

### PR DESCRIPTION
**Pull request by fazaza**
Support for setting Elasticsearch Preference in the Query Apis

- [ ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAES).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by fazaza** [comment]
Thanks for review, will update soon ...

**Comment by fazaza** [comment]
Please find below update :

- ElasticsearchTemplate : add test for valid / invalid preference

- ElasticsearchRestTemplate : already tested in super class ElasticsearchTemplateTests
for the invalid preference test there is a different Exception type ( llegalArgumentException in case of ElasticsearchTemplate and ElasticsearchStatusException in case of ElasticsearchRestTemplate ), 	this is why I expect generic Exception
let me know if you prefer to do it in another way

- ReactiveElasticSearchTemplate : support preference and add test for valid / invalid preference

**Comment by sothawo** [comment]
I adpated the Jira issue title to "_Support for setting preference parameter in query_", so please squash your commits to a single one with the message "_DATAES-595 - Support for setting preference parameter in query._"; then I'm fine with this PR.

**Comment by fazaza** [comment]
done, please review

**Comment by sothawo** [comment]
the PR has been merged; thank you for the contribution!

when submitting the next PR, please check of the boxes in the guidance form at the top of the PR with _x_.

**Pull request merged**
