### PR TITLE
DATAES-494 - ElasticTemplates refactoring.

### PR DESCRIPTION
**Pull request by Guchman**
Only refactoring changes. ElasticRestTemplate and ElasticTemplate had a lot of duplicate logic. Now extends AbstractElasticTemplate and use several util classes.

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAES).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by Guchman** [comment]
Ok, will fix soon. But I had apply Eclipse plugin for imports. So imports must follow guidelines(second commit). I could ammend both commits if it would be easier for you to review.
Also, when I extract part of the code to separate class, should I add all authors of the original class or just authors of extracted part?

**Comment by odrotbohm** [comment]
@ authors – Yes, please.

Generally speaking I'd recommend to move slowly for now as we're planning some more fundamental changes to the inner workings and I sense that your changes might overlap here. @christophstrobl can probably advise.

**Comment by Guchman** [comment]
@odrotbohm Sorry, but where could I find all guidelines? I check contribution guide again and there is no mention of method order and final variables. I'm missing something?

**Comment by Guchman** [comment]
@odrotbohm Is there any chance for merge this? 
If not please tell me why and lets close this PR.
Or tell me what I should do to be merged. Thanks

**Comment by xhaggi** [comment]
Superseded by #278

**Pull request closed without merging**
